# Generated by Django 5.1.3 on 2024-11-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efficientlyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='profile_pic.jpg', upload_to='profile_pics'),
        ),
    ]
